/**
 * A token type enumeration.
 */
enum TokenType {
  /**
   * A token representing a let statement.
   */
  LET,
  /**
   * A token representing an equal sign.
   */
  EQUAL,
  /**
   * A token representing a number.
   */
  NUMBER,
  /**
   * A token representing a comment.
   */
  COMMENT,
  /**
   * A token representing a let statement.
   */
  LET,
  /**
   * A token representing a string literal.
   */
  STRING
}

/**
 * A token representing a let statement.
 */
class Token {
  type: TokenType;
  value: string;

  constructor(type: TokenType, value: string) {
    this.type = type;
    this.value = value;
  }
}

/**
 * A finite state machine tokenizer.
 */
class Tokenizer {
  private readonly states: { [key: string]: string[]; } = {
    "start": ["LET", "EQUAL", "NUMBER", "COMMENT", "LET", "STRING"],
    "whitespace": ["WHITESPACE"],
    "comment": ["COMMENT"],
    "whitespace": ["WHITESPACE"],
    "let_statement": ["LET"],
    "equal_sign": ["EQUAL"],
    "number": ["NUMBER"],
    "string_literal": ["STRING"],
    "whitespace": ["WHITESPACE"],
    "comment": ["COMMENT"],
    "let_statement": ["LET"],
    "equal_sign": ["EQUAL"],
    "number": ["NUMBER"],
    "string_literal": ["STRING"],
    "whitespace": ["WHITESPACE"],
    "comment": ["COMMENT"],
    "let_statement": ["LET"],
    "equal_sign": ["EQUAL"],
    "number": ["NUMBER"],
    "string_literal": ["STRING"],
    "whitespace": ["WHITESPACE"],
    "comment": ["COMMENT"],
    "let_statement": ["LET"],
    "equal_sign": ["EQUAL"],
    "number": ["NUMBER"],
    "string_literal": ["STRING"],
    "whitespace": ["WHITESPACE"],
    "comment": ["COMMENT"],
    "let_statement": ["LET"],
    "equal_sign": ["EQUAL"],
    "number": ["NUMBER"],
    "string_literal": ["STRING"],
    "whitespace": ["WHITESPACE"],
    "comment": ["COMMENT"],
    "let_statement": ["LET"],
    "equal_sign": ["EQUAL"],
    "number": ["NUMBER"],
    "string_literal": ["STRING"],
    "whitespace": ["WHITESPACE"],
    "comment": ["COMMENT"],
    "let_statement": ["LET"],
    "equal_sign": ["EQUAL"],
    "number": ["NUMBER"],
    "string_literal": ["STRING"],
    "whitespace": ["WHITESPACE"],
    "comment": ["COMMENT"],
    "let_statement": ["LET"],
    "equal_sign": ["EQUAL"],
    "number": ["NUMBER"],
    "string_literal": ["STRING"],
    "whitespace": ["WHITESPACE"],
    "comment": ["COMMENT"],
    "let_statement": ["LET"],
    "equal_sign": ["EQUAL"],
    "number": ["NUMBER"],
    "string_literal": ["STRING"],
    "whitespace": ["WHITESPACE"],
    "comment": ["COMMENT"],
    "let_statement": ["LET"],
    "equal_sign": ["EQUAL"],
    "number": ["NUMBER"],
    "string_literal": ["STRING"],
    "whitespace": ["WHITESPACE"],
    "comment": ["COMMENT"],
    "let_statement": ["LET"],
    "equal_sign": ["EQUAL"],
    "number": ["NUMBER"],
    "string_literal": ["STRING"],
    "whitespace": ["WHITESPACE"],
    "comment": ["COMMENT"],
    "let_statement": ["LET"],
   "equal_sign": ["EQUAL"],
   "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
  "let_statement": ["LET"],
  "equal_sign": ["EQUAL"],
  "number": ["NUMBER"],
  "string_literal": ["STRING"],
  "whitespace": ["WHITESPACE"],
  "comment": ["COMMENT"],
}
}
